early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: val/total_loss
  min_delta: 1e-6
  patience: 3
  verbose: false
  mode: min
  check_finite: true
  stopping_threshold: null
  divergence_threshold: null
  check_on_train_epoch_end: false