defaults:
  - _self_
  # disable any hydra logging and directory creation
  - history_serializer: zipped
  - state_serializer: key_value_state_changes
  - schema_serializer: simple
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled

hydra:  
  output_subdir: null  
  run:  
    dir: .
  job:
    chdir: false

sep_token: '<sep>'
input_template: null
target_template: '\$states'

# I/O
tokenizer: '???'
output_dir: '???'
input_dir: '???'

# SGD stuff that might go away in the future
format: null
n_splits: null
unify: false

# processing
padded_state: false
lowercase: false
